### ISSUE TITLE
Update purescript-argonaut-aeson-generic

### ISSUE THREAD

**Issue by peterbecich** [purescript/registry#88] opened 2022-11-20 07:57 UTC
```json
{
  "name": "purescript-argonaut-aeson-generic",
  "ref": "v0.4.0",
  "compiler": "0.15.4",
  "location": {
    "githubOwner": "peterbecich",
    "githubRepo": "purescript-purescript-argonaut-aeson-generic"
  },
}
```

This package is currently maintained here: https://github.com/coot/purescript-argonaut-aeson-generic/
I am attempting to become a maintainer per this discussion: https://github.com/coot/purescript-argonaut-aeson-generic/pull/17#issuecomment-1299650538
We would like to maintain the package here: https://github.com/peterbecich/purescript-argonaut-aeson-generic

**Comment by thomashoneyman** [comment] 2022-11-20 13:53
```json
{
  "name": "purescript-argonaut-aeson-generic",
  "ref": "v0.4.0",
  "compiler": "0.15.4",
  "location": {
    "githubOwner": "peterbecich",
    "githubRepo": "purescript-purescript-argonaut-aeson-generic"
  }
}
```

Unfortunately our JSON parser bails on trailing commas — if I have some time today I can try to make it more lenient. Resubmitting the payload for you.

**Comment by thomashoneyman** [comment] 2022-11-20 14:00
This is not a good error message; the issue is that package names with a purescript- prefix are disallowed in general because of the historical confusion between repos using the prefix (purescript-aff) and package names not using the prefix (aff).

If you really want the package name to use a PureScript prefix then I can allowlist it for you.

**Comment by f-f** [comment] 2022-11-20 16:19
This needs to be specced properly, but I think we shouldn't add things to the allowlist unless there's a clear reason (or why would we bother to have an allowlist at all)

This one looks like a fairly normal package though?

**Comment by thomashoneyman** [comment] 2022-11-20 16:29
The reason for the allowlist is to prevent people from inadvertently registering their package as e.g. “purescript-aff”, which it would have been in the Bower days, when they really ought to use “aff.”

However, sometimes you really _do_ want to use the prefix, but it’s exceedingly rare. Right now only one package uses it. It’s typically for packages that do something with the PureScript language itself.

When implementing this restriction we’d agreed that people should be able to use the prefix if they ask to. Conversations like this one might give them reason to omit it, though!

**Comment by f-f** [comment] 2022-11-20 16:37
I don't think we should be liberal about it - the danger is that we could then easily end up in a situation where half of the packages use the `purescript-` prefix (because they asked to), and half of them don't.

This is confusing! Imagine someone wanting to register `purescript-aff`, a totally different package than `aff`. Would we allow them?

If we would then we should entirely get rid of the whole "stripping the purescript prefix" thing and just let everyone do whatever, because we'd be just embracing the chaos.
If we wouldn't then we are _not_ being liberal about it, and "just asking" is definitely not enough to enter the allowlist.

**Comment by tonicebrian** [comment] 2022-11-20 18:24
Also watchout that the repo is wrong:

```
    "githubRepo": "purescript-purescript-argonaut-aeson-generic"
```

two `purescripts`  in the name

**Comment by f-f** [comment] 2022-11-20 18:31
> An alternative is to only allowlist legacy packages (those that predate the registry), of which there is just 1 package. No packages have since been registered attempting to use the prefix except this one.

Yeah I think we should consider this not available unless we stumble on a package which truly deserves an exception. In that case we can think about it, and eventually allow it at the discretion of the Trustees

**Comment by thomashoneyman** [comment] 2022-11-20 18:41
> Yes, it’s a bit arbitrary right now. An alternative is to only allowlist legacy packages (those that predate the registry), of which there is just 1 package. No packages have since been registered attempting to use the prefix except this one.

Reposting this since I accidentally used the pacchettibotti account — this was me!

> Yeah I think we should consider this not available unless we stumble on a package which truly deserves an exception. In that case we can think about it, and eventually allow it at the discretion of the Trustees

Works for me. This pretty much goes back to “ask us”, so it would still be nice to clarify what is likely to be accepted (ie nothing unless there’s a name conflict or it predates the registry)

**Comment by peterbecich** [comment] 2022-11-20 20:44
Thanks all. I am attempting to update https://pursuit.purescript.org/packages/purescript-argonaut-aeson-generic . Should I submit a new `purescript/registry` issue with this payload?

```
{
  "name": "argonaut-aeson-generic",
  "ref": "v0.4.0",
  "compiler": "0.15.4",
  "location": {
    "githubOwner": "peterbecich",
    "githubRepo": "purescript-argonaut-aeson-generic"
  }
}
```

**Comment by f-f** [comment] 2022-11-20 20:49
@peterbecich adding new comments to this issue works as well, no need to open a new one.

This payload is not going to work, because a package with the same name already exists, and the only person that can transfer this name to you is the package author, either by transferring the GitHub package to your user, or by giving you write access so you can perform a [Transfer operation](https://github.com/purescript/registry-dev/blob/master/SPEC.md#54-transfer-a-package-authenticated) (but if you had write access you wouldn't need to fork the package in the first place).
If you wish to register a fork of the package you'll have to pick a new name.

**Comment by peterbecich** [comment] 2022-11-20 20:50
Thanks @f-f

**Closed** 2022-12-07 18:14 UTC
